# This file was generated by GoReleaser. DO NOT EDIT.
cask "shellcade-kit" do
  version "2.13.0"

  on_macos do
    on_intel do
      sha256 "1e957dd6cc2556317e8f76ba8fb76ccf915fec004ba3faab5b0757e44162187b"
      url "https://github.com/shellcade/kit/releases/download/v#{version}/shellcade-kit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a722ff0016eb8c1534548a80ee4309614f17f1a947f394f572e252233dc3a7ca"
      url "https://github.com/shellcade/kit/releases/download/v#{version}/shellcade-kit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7fbcbc9b25d4f837fb39a7e91d409af26ec593522be52045c4a56b349c9d581b"
      url "https://github.com/shellcade/kit/releases/download/v#{version}/shellcade-kit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "66e5bce0bcce67ca9d1d71aa1173b93d48c42c9e65718f1e71e3e5d02c693c27"
      url "https://github.com/shellcade/kit/releases/download/v#{version}/shellcade-kit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "shellcade-kit"
  desc "shellcade game developer kit: scaffold, verify, and play wasm games"
  homepage "https://github.com/shellcade/kit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shellcade-kit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shellcade-kit"]
    end
  end

  # No zap stanza required

end
