# This file was generated by GoReleaser. DO NOT EDIT.
cask "shellcade-kit" do
  version "2.1.1"

  on_macos do
    on_intel do
      sha256 "4439d6e16cb588a9937e9f8571f3e9450dca021ffbe481b6e6e6b0d36a294540"
      url "https://github.com/shellcade/kit/releases/download/v#{version}/shellcade-kit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cc8c39e9b43783b80aed08826a44985be7c3ed6c07228f161241bcdf60ea68ac"
      url "https://github.com/shellcade/kit/releases/download/v#{version}/shellcade-kit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b2575c3cc2f5ed7cb3f4ae5ffcd28fc225940193e99289756ea1e89b5587425c"
      url "https://github.com/shellcade/kit/releases/download/v#{version}/shellcade-kit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b5c0a1971479fdf7c41bda110f774620ccf9b63fa6710f70083f777a3692c38"
      url "https://github.com/shellcade/kit/releases/download/v#{version}/shellcade-kit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "shellcade-kit"
  desc "shellcade game developer kit: scaffold, verify, and play wasm games"
  homepage "https://github.com/shellcade/kit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shellcade-kit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shellcade-kit"]
    end
  end

  # No zap stanza required

end
