# This file was generated by GoReleaser. DO NOT EDIT.
cask "shellcade-kit" do
  version "2.14.0"

  on_macos do
    on_intel do
      sha256 "2a16b811ce7402c03b0310ee1a43e0d23d0b1cf06ca14508a7fedd920ce07b95"
      url "https://github.com/shellcade/kit/releases/download/v#{version}/shellcade-kit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "98a7e7d3dea59ebfc4e612d805e70f0a316c7fd0a6ba391be07a457b63a07659"
      url "https://github.com/shellcade/kit/releases/download/v#{version}/shellcade-kit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1baba4a3e00ad89e061ed604ffb424a8121aab6f51b9d47b76d55c209b5af240"
      url "https://github.com/shellcade/kit/releases/download/v#{version}/shellcade-kit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "666b229b2523c0ef7534000c82aa811086bdad8bb95552c52df10258d6028a4b"
      url "https://github.com/shellcade/kit/releases/download/v#{version}/shellcade-kit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "shellcade-kit"
  desc "shellcade game developer kit: scaffold, verify, and play wasm games"
  homepage "https://github.com/shellcade/kit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shellcade-kit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shellcade-kit"]
    end
  end

  # No zap stanza required

end
